/*"1) If person (no conscious and no breathing and no bleeding and no electric shock and no major trauma and no car accident) then Call 112+CPR+AED	"						
2) If person (no conscious and no breathing and no bleeding and electric shock) then Turn off the power source+ Don't cover burnts+ Call 112+CPR+AED						
3) If person (no conscious and no breathing and no bleeding and no electric shock and major trauma and no car accident) then Call 112+Don't move person+CPR+AED						
4)If person (no conscious and no  breathing and bleeding and major trauma and no car accident) then Call 112+ Pressure+Don't move person+CPR+AED						
5)If person (no conscious and breathing and no bleeding and major trauma and car accident) then P (Proteger)+ A (Avisar: Call 112) +S (Socorrer: Don't move person or remove helmet, protect from cold or heat, don't give food or drinks)						
6)If person (no conscious and no breathing and no bleeding and no electric shock and  major trauma and car accident) then P (Proteger)+ A (Avisar: Call 112) +S (Socorrer: Don't move person or remove helmet...+CPR+AED)						
"7)If person(no conscious and no breathing and bleeding and major trauma and car accident ) then P (Proteger)+ A (Avisar: Call 112) +S (Socorrer: Pressure+Don't move person or remove helmet...+CPR+AED)	"						
8)If person (conscious and no dizzy and emit words and trying to cough and difficulty breathing) then Encourage to cough						
9)If person (conscious and no dizzy and no emit words and difficulty breathing) then Heimlich M.						
10)If person (chest pain) then Call 112+Look for medication						
11) If person (no conscious and breathing and no bleeding and no major trauma and no vomit) then Secure area+ Legs up, loosen tight clothing+Call 112 if not recovered						
"12) If person (no conscious and breathing and no bleeding and no major trauma and vomit) then Secure area+ Recovery position+Call 112	if not recovered"						
13)If person ( conscious and dizzy and no bleeding) then Lay down, legs up+ Loosen tight clothing+ Hydration						
14) If person (conscious and dizzy and  bleeding) then Pressure to wound						
"15) If person (no conscious and no breathing and no bleeding and seizure) then Secure area+Cushion head...+Recovery position+Call 112	if not recovered"						
16) If person (conscious and no dizzy and emit words and no trying to cough and  Suspicion of intoxication/ poisoning and difficulty breathing ) then Call 915 620420+Recovery position, fresh air						
17) If person (conscious and no dizzy and emit words and no trying to cough and no Suspicion of intoxication/ poisoning and no vomit and difficulty breathing ) then Call 915 620420+ Epinephrine+ Lay down						
18) If person (conscious and no dizzy and emit words and no trying to cough and no Suspicion of intoxication/ poisoning and vomit and difficulty breathing ) then Call 915 620420+ Epinephrine+ Recovery position						
19)If person (conscious and trying to cough and difficulty breathing) then Inhaler+ Keep calm						
20)If person( conscious and difficulty breathing) then Call 112+loosen tight clothes						
21)If person (conscious and dizzy and breathing and no emit words ) then Call 112						
22) If person (conscious and no dizzy and emit words and difficulty breathing) then Deep breathing + distraction + psycological first aids*/

import objects.MedicalEmergency						

rule "Emergency Response 1"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "no",
                                  bleeding == "no")
then
    System.out.println("Call 112");
    System.out.println("Start CPR");
    System.out.println("Use AED (Automated External Defibrillator)");
end

rule "Emergency Response 2"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "no",
                                  bleeding == "no",
                                  electric_shock == "yes")                                    )
then
    System.out.println("Turn off the power source");
    System.out.println("Do not cover burnts");
    System.out.println("Call 112");
    System.out.println("Start CPR");
    System.out.println("Use AED (Automated External Defibrillator)");
end

rule "Emergency Response 3"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "no",
                                  bleeding == "no",
                                  electric_shock == "yes",
                                  major_trauma == "yes",
                                  car_accident == "no")
then
    System.out.println("Call 112");
    System.out.println("Do not move the person");
    System.out.println("Start CPR");
    System.out.println("Use AED (Automated External Defibrillator)");
end

rule "Emergency Response 4"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "no",
                                  bleeding == "yes",
                                  major_trauma == "yes",
                                  car_accident == "no")
then
    System.out.println("Call 112");
    System.out.println("Apply pressure to stop bleeding");
    System.out.println("Do not move the person");
    System.out.println("Start CPR");
    System.out.println("Use AED (Automated External Defibrillator)");
end

rule "Emergency Response 5"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "yes",
                                  bleeding == "no",
                                  major_trauma == "yes",
                                  car_accident == "yes")
then
    System.out.println("Protect the person");
    System.out.println("Call 112");
    System.out.println("Do not move the person or remove helmet, protect from cold or heat, don't give food or drinks");
end

rule "Emergency Response 5"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "yes",
                                  bleeding == "no",
                                  major_trauma == "yes",
                                  car_accident == "yes")
then
    System.out.println("Protect the person");
    System.out.println("Call 112");
    System.out.println("Do not move the person or remove helmet, protect from cold or heat, don't give food or drinks");
end

rule "Emergency Response 6"
dialect "java"
when
    $emergency : MedicalEmergency(conscious == "no",
                                  breathing == "no",
                                  bleeding == "no",
                                  electric_shock == "no",
                                  major_trauma == "yes",
                                  car_accident == "yes")
then
    System.out.println("Protect the person");
    System.out.println("Call 112");
    System.out.println("Do not move the person or remove helmet, protect from cold or heat, don't give food or drinks");
    System.out.println("Start CPR");
    System.out.println("Use AED (Automated External Defibrillator)");
end